In [1]:
import pandas as pd
import numpy as np
import sys

try:
    import tsad
except:
    import sys
    sys.path.insert(1, '../')
    
import warnings
warnings.filterwarnings('ignore')

from tsad.utils.evaluating.evaluating import evaluating

In [2]:
true = pd.Series(0,pd.date_range('2020-01-01','2020-01-20',freq='D'))
true.iloc[[6,14]]=1

prediction = pd.Series(0,pd.date_range('2020-01-01','2020-01-20',freq='D'))
prediction.iloc[[4,10]]=1

pd.concat([true,prediction],1).rename({0:'True',1:'Predict'},axis=1).reset_index()

        index  True  Predict
0  2020-01-01     0        0
1  2020-01-02     0        0
2  2020-01-03     0        0
3  2020-01-04     0        0
4  2020-01-05     0        1
5  2020-01-06     0        0
6  2020-01-07     1        0
7  2020-01-08     0        0
8  2020-01-09     0        0
9  2020-01-10     0        0
10 2020-01-11     0        1
11 2020-01-12     0        0
12 2020-01-13     0        0
13 2020-01-14     0        0
14 2020-01-15     1        0
15 2020-01-16     0        0
16 2020-01-17     0        0
17 2020-01-18     0        0
18 2020-01-19     0        0
19 2020-01-20     0        0

In [5]:
results = evaluating(true=true,
                     prediction=prediction,
                     metric ='average_time',
                     window_width='3D',
                     anomaly_window_destination='lefter')

Amount of true anomalies 2
A number of missed CPs = 1
A number of FPs = 1
Average time 2 days 00:00:00

In [6]:
results = evaluating(true=true,prediction=prediction,)
print(results)

Since you didn't choose window_width and portion, portion will be default (0.1)
Standard  -  -5.5
LowFP  -  -11.0
LowFN  -  -3.67
{'Standard': -5.5, 'LowFP': -11.0, 'LowFN': -3.67}